version: "3.5"
services:
  manager-task-api:
    container_name: manager-task-api
    build: .
    restart: always

    ports:
      - "4000:4000"
    volumes:
      - .:/app/manager-task-api
      - node-modules-manager-task-api:/app/manager-task-api/node_modules

volumes:
  node-modules-manager-task-api:
    name: node-modules-manager-task-api
