version: "3.5"
services:
  manager-task-api:
    container_name: manager-task-api
    build: .
    restart: always
    depends_on:
      - mysql
    ports:
      - "3333:3333"
    volumes:
      - .:/app/manager-task-api
      - node-modules-manager-task-api:/app/manager-task-api/node_modules
    networks:
      - mysql-network

  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql:rw
    restart: always
    environment:
      MYSQL_DATABASE: manager-task
      MYSQL_ROOT_PASSWORD: password
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge

volumes:
  node-modules-manager-task-api:
    name: node-modules-manager-task-api
  mysql:
    name: mysql
